
import com.sun.prism.paint.Color;
import java.awt.Image;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AddNew extends javax.swing.JFrame {

    /**
     * Creates new form AddNew
     */
    String imagepth = null;

    public AddNew() {
        initComponents();
        this.setLocationRelativeTo(null);
        //scaleimage();
        this.setOpacity(0.8f);
    }

    /* public void scaleimage() {

        ImageIcon icon = new ImageIcon("F:\\New folder\\2.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(Pic.getWidth(), Pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        Pic.setIcon(scaledIcon);
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BNM = new javax.swing.JTextField();
        PID = new javax.swing.JTextField();
        Quan = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BookPic = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BNM.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        BNM.setBorder(null);
        BNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNMActionPerformed(evt);
            }
        });
        jPanel1.add(BNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 29));

        PID.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        PID.setBorder(null);
        jPanel1.add(PID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 29));

        Quan.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        Quan.setBorder(null);
        Quan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanActionPerformed(evt);
            }
        });
        jPanel1.add(Quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, 29));

        price.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        price.setBorder(null);
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 190, 29));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel1.setText("Book Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 161, 100, 29));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel2.setText("Price           :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel3.setText("Image        :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel4.setText("Product ID  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 110, 100, 29));

        jLabel5.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Quantity    :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 30));

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 20, -1));

        BookPic.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(BookPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 150, 80));

        jButton2.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        edit.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 80, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 193, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 190, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 190, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 190, 10));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setToolTipText("");
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 80));

        cancel.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.setActionCommand("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 389, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // if (verifdata()) {
        String pid = PID.getText();
        String bname = BNM.getText();
        String quantity = Quan.getText();
        String Pri = price.getText();
        //String id =cid.getText();
        if (imagepth != null) { //if the user want to update with image
            byte[] img = null;
            try {
                Path pth = Paths.get(imagepth);
                img = Files.readAllBytes(pth);
                list c = new list(pid, bname, quantity, Pri, img);
                listQuery cq = new listQuery();
                cq.updateList(c, true);

            } catch (IOException ex) {
                Logger.getLogger(AddNew.class.getName()).log(Level.SEVERE, null, ex);
            }
        } /*if (isPidexit(PID.getText())) {
                JOptionPane.showMessageDialog(null, "This Product Id Already Exits", "Failed", HEIGHT);
            }*/ else {
            list c = new list(pid, bname, quantity, Pri, null);
            listQuery cq = new listQuery();
            cq.updateList(c, false);
        }
        //}
        // this.dispose();
    }//GEN-LAST:event_editActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (verifdata()) {
            String pid = PID.getText();
            String bname = BNM.getText();
            String quantity = Quan.getText();
            String Pri = price.getText();
            //String id =cid.getText();
            byte[] img = null;
            try {
                Path pth = Paths.get(imagepth);
                img = Files.readAllBytes(pth);
            } catch (IOException ex) {
                Logger.getLogger(AddNew.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (isPidexit(PID.getText())) {
                JOptionPane.showMessageDialog(null, "This Product Id Already Exits", "Failed", HEIGHT);
            } else {
                list c = new list(pid, bname, quantity, Pri, img);
                listQuery cq = new listQuery();
                cq.insertList(c);

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser filec = new JFileChooser();
        filec.setCurrentDirectory(new File(System.getProperty("user.home")));
        //Extension
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg", "png", "gif");
        filec.addChoosableFileFilter(filter);
        int FileState = filec.showOpenDialog(null);
        if (FileState == JFileChooser.APPROVE_OPTION) {
            File selectedFile = filec.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            imagepth = path;
            //display
            BookPic.setIcon(resizePic(path));
        } else if (FileState == JFileChooser.CANCEL_OPTION) {
            System.out.println("No Image Selected");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void QuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuanActionPerformed

    private void BNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BNMActionPerformed
    private int xMouse, yMouse;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        this.dispose();       
    }//GEN-LAST:event_cancelMouseClicked
    public ImageIcon resizePic(String picpath) {
        ImageIcon myImage = new ImageIcon(picpath);
        Image img = myImage.getImage().getScaledInstance(BookPic.getWidth(), BookPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon myPicture = new ImageIcon(img);
        return myPicture;
    }

    public boolean verifdata() {
        if (PID.getText().equals("") || BNM.getText().equals("") || Quan.getText().equals("") || price.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Some field missing", "Failed", HEIGHT);
            return false;
        } else if (imagepth == null) {
            JOptionPane.showMessageDialog(null, "Image missing", "Failed", HEIGHT);
            return false;
        } else {
            return true;
        }
    }

    public boolean isPidexit(String pi) {
        boolean pExit = false;
        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * FROM `addbook` WHERE  `ProductID` = ?";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, PID.getText());
            rs = ps.executeQuery();

            if (rs.next()) {
                pExit = true;
            }

        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return pExit;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BNM;
    private javax.swing.JLabel BookPic;
    private javax.swing.JTextField PID;
    private javax.swing.JTextField Quan;
    private javax.swing.JButton cancel;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
