
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class Admin extends javax.swing.JFrame {

    public Admin() {
        initComponents();
        populateJtable();
        populateJtable1();
        jTable.setShowGrid(true);
        jTable.setGridColor(Color.white);
        this.setLocationRelativeTo(null);  //center to the screen
        scaleimage();

    }

    public void scaleimage() {

        ImageIcon icon = new ImageIcon("F:\\New folder\\2.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(Pic.getWidth(), Pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        Pic.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Pic = new javax.swing.JLabel();
        jT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        ADD = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Remove = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ulist = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        logout = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        olist = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        home1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Pic.setText("jLabel1");
        jPanel1.add(Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 110));

        jT.setBackground(new java.awt.Color(51, 51, 51));
        jT.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jT.setForeground(new java.awt.Color(255, 255, 255));
        jT.setBorder(null);
        jT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTActionPerformed(evt);
            }
        });
        jT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTKeyTyped(evt);
            }
        });
        jPanel1.add(jT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 370, 30));

        jTable.setBackground(new java.awt.Color(0, 102, 153));
        jTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTable.setForeground(new java.awt.Color(255, 255, 255));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable.setAlignmentX(0.8F);
        jTable.setAlignmentY(0.8F);
        jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable.setGridColor(new java.awt.Color(0, 0, 0));
        jTable.setSelectionBackground(new java.awt.Color(0, 102, 153));
        jScrollPane2.setViewportView(jTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 800, 340));

        ADD.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setText(">>Add New");
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDMouseExited(evt);
            }
        });
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 26));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 107, 10));

        Remove.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        Remove.setForeground(new java.awt.Color(255, 255, 255));
        Remove.setText(">>Remove");
        Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemoveMouseExited(evt);
            }
        });
        jPanel1.add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 26));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 108, 10));

        ulist.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        ulist.setForeground(new java.awt.Color(255, 255, 255));
        ulist.setText(">>User List");
        ulist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ulistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ulistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ulistMouseExited(evt);
            }
        });
        jPanel1.add(ulist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 26));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, 108, 10));

        logout.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText(">>Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 110, 26));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 370, 30));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 60, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 110, 10));

        olist.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        olist.setForeground(new java.awt.Color(255, 255, 255));
        olist.setText(">>Order List");
        olist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                olistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                olistMouseExited(evt);
            }
        });
        jPanel1.add(olist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, 26));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 110, 10));

        home1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        home1.setForeground(new java.awt.Color(255, 255, 255));
        home1.setText(">>Home");
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home1MouseExited(evt);
            }
        });
        jPanel1.add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populateJtable() {
        listQuery cq = new listQuery();
        ArrayList<list> ctlist = cq.bookList();
        String[] colName = {"Product Id", "Book Name", "Quantity", "Price", "Image"};
        Object[][] rows = new Object[ctlist.size()][5];
        for (int i = 0; i < ctlist.size(); i++) {
            rows[i][0] = ctlist.get(i).getPID();
            rows[i][1] = ctlist.get(i).getBNM();
            rows[i][2] = ctlist.get(i).getPrice();
            rows[i][3] = ctlist.get(i).getQuan();
            ImageIcon pic = new ImageIcon(new ImageIcon(ctlist.get(i).getBookPic()).getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH));
            rows[i][4] = pic;

            MyModel mmd = new MyModel(rows, colName);
            jTable.setModel(mmd);
            jTable.setRowHeight(60);
            jTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        }
    }

    public void populateJtable1() {
        listQuery cq = new listQuery();
        //String valueToSeach;

        ArrayList<list> ctlist = cq.bookList1(jT.getText());

        String[] colName = {"Product Id", "Book Name", "Quantity", "Price", "Image"};
        Object[][] rows = new Object[ctlist.size()][5];
        for (int i = 0; i < ctlist.size(); i++) {
            rows[i][0] = ctlist.get(i).getPID();
            rows[i][1] = ctlist.get(i).getBNM();
            rows[i][2] = ctlist.get(i).getPrice();
            rows[i][3] = ctlist.get(i).getQuan();
            ImageIcon pic = new ImageIcon(new ImageIcon(ctlist.get(i).getBookPic()).getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH));
            rows[i][4] = pic;
            //  jTable.getColumnModel().getColumn(1).setPreferredWidth(40);
            MyModel mmd = new MyModel(rows, colName);
            jTable.setModel(mmd);
            jTable.setRowHeight(60);
            jTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        }
    }


    private void jTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTActionPerformed

    }//GEN-LAST:event_jTActionPerformed

    private void jTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTKeyTyped
        if (jT.getText() == "") {
            populateJtable();
        } else {
            populateJtable1();
        }

    }//GEN-LAST:event_jTKeyTyped

    private void jTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTKeyReleased

    }//GEN-LAST:event_jTKeyReleased

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
        AddNew rgf = new AddNew();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        // rgf.setExtendedState(JFrame.MAXIMIZED_BOTH);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // this.dispose();
    }//GEN-LAST:event_ADDMouseClicked

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered
        ADD.setBackground(Color.LIGHT_GRAY);
        ADD.setOpaque(true);
    }//GEN-LAST:event_ADDMouseEntered

    private void ADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseExited
        ADD.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ADDMouseExited

    private void RemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseEntered
        Remove.setBackground(Color.LIGHT_GRAY);
        Remove.setOpaque(true);
    }//GEN-LAST:event_RemoveMouseEntered

    private void RemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseExited
        Remove.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_RemoveMouseExited

    private void ulistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ulistMouseEntered
        ulist.setBackground(Color.LIGHT_GRAY);
        ulist.setOpaque(true);
    }//GEN-LAST:event_ulistMouseEntered

    private void ulistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ulistMouseExited
        ulist.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ulistMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(Color.LIGHT_GRAY);
        logout.setOpaque(true);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_logoutMouseExited

    private void ulistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ulistMouseClicked
        listQuery cq = new listQuery();
        ArrayList<ulist> ctlist = cq.userList();
        String[] colName = {"First Name", "Last Name", "Phone", "Username", "Password"};
        Object[][] rows = new Object[ctlist.size()][5];
        for (int i = 0; i < ctlist.size(); i++) {
            rows[i][0] = ctlist.get(i).getfname();
            rows[i][1] = ctlist.get(i).getlname();
            rows[i][2] = ctlist.get(i).getphone();
            rows[i][3] = ctlist.get(i).getuser();
            rows[i][4] = ctlist.get(i).getpass();

            MyModel mmd = new MyModel(rows, colName);
            jTable.setModel(mmd);
            jTable.setRowHeight(60);
            jTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        }
    }//GEN-LAST:event_ulistMouseClicked

    private void olistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olistMouseEntered
        olist.setBackground(Color.LIGHT_GRAY);
        olist.setOpaque(true);
    }//GEN-LAST:event_olistMouseEntered

    private void olistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olistMouseExited
        olist.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_olistMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login rgf = new login();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseClicked
        delete rgf = new delete();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //this.dispose();
    }//GEN-LAST:event_RemoveMouseClicked

    private void home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseClicked
        Admin rgf = new Admin();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_home1MouseClicked

    private void home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseEntered
        home1.setBackground(Color.LIGHT_GRAY);
        home1.setOpaque(true);
    }//GEN-LAST:event_home1MouseEntered

    private void home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseExited
        home1.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_home1MouseExited

    private void olistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olistMouseClicked

        listQuery cq = new listQuery();
        ArrayList<olist> ctlist = cq.orderList();
        String[] colName = {"Customer Name", "Product ID", "Quantity", "Phone No","Address"};
        Object[][] rows = new Object[ctlist.size()][5];
        for (int i = 0; i < ctlist.size(); i++) {
            rows[i][0] = ctlist.get(i).getYnameF();
            rows[i][1] = ctlist.get(i).getPidF();
            rows[i][2] = ctlist.get(i).getQuantityF();
            rows[i][3] = ctlist.get(i).getPhoneF();
            rows[i][4] = ctlist.get(i).getAddressF();

            MyModel mmd = new MyModel(rows, colName);
            jTable.setModel(mmd);
            jTable.setRowHeight(60);
            jTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        }


    }//GEN-LAST:event_olistMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADD;
    private javax.swing.JLabel Pic;
    private javax.swing.JLabel Remove;
    private javax.swing.JLabel home1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jT;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel olist;
    private javax.swing.JLabel ulist;
    // End of variables declaration//GEN-END:variables
}
