
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePagegfgf
     */
    public HomePage() {
        initComponents();
        populateJtable();
        populateJtable1();
        //  populateJtable2();
        jTable.setShowGrid(true);
        jTable.setGridColor(Color.white);
        this.setLocationRelativeTo(null);  //center to the screen
        scaleimage();
    }

    public void scaleimage() {

        ImageIcon icon = new ImageIcon("F:\\New folder\\2.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(Pic.getWidth(), Pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        Pic.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pic = new javax.swing.JLabel();
        jT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        home = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        order = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        olist = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Pic.setText("jLabel1");
        jPanel1.add(Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 940, 120));

        jT.setBackground(new java.awt.Color(51, 51, 51));
        jT.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jT.setForeground(new java.awt.Color(255, 255, 255));
        jT.setBorder(null);
        jT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTActionPerformed(evt);
            }
        });
        jT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTKeyTyped(evt);
            }
        });
        jPanel1.add(jT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 370, 30));

        jTable.setBackground(new java.awt.Color(0, 102, 153));
        jTable.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTable.setForeground(new java.awt.Color(255, 255, 255));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable.setAlignmentX(0.8F);
        jTable.setAlignmentY(0.8F);
        jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable.setGridColor(new java.awt.Color(0, 0, 0));
        jTable.setSelectionBackground(new java.awt.Color(0, 102, 153));
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 800, 360));

        home.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText(">>Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 26));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 107, 13));

        order.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        order.setForeground(new java.awt.Color(255, 255, 255));
        order.setText(">>Order");
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderMouseExited(evt);
            }
        });
        jPanel1.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 26));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 108, 10));

        olist.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        olist.setForeground(new java.awt.Color(255, 255, 255));
        olist.setText(">>Log Out");
        olist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                olistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                olistMouseExited(evt);
            }
        });
        jPanel1.add(olist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 26));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 370, 30));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populateJtable() {
        listQuery cq = new listQuery();
        ArrayList<list> ctlist = cq.bookList();
        String[] colName = {"Product Id", "Book Name", "Quantity", "Price", "Image"};
        Object[][] rows = new Object[ctlist.size()][5];
        for (int i = 0; i < ctlist.size(); i++) {
            rows[i][0] = ctlist.get(i).getPID();
            rows[i][1] = ctlist.get(i).getBNM();
            rows[i][2] = ctlist.get(i).getPrice();
            rows[i][3] = ctlist.get(i).getQuan();
            ImageIcon pic = new ImageIcon(new ImageIcon(ctlist.get(i).getBookPic()).getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH));
            rows[i][4] = pic;

            MyModel mmd = new MyModel(rows, colName);
            jTable.setModel(mmd);
            jTable.setRowHeight(40);
            //jTable.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTable.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable.getColumnModel().getColumn(4).setPreferredWidth(40);

        }
    }

    public void populateJtable1() {
        listQuery cq = new listQuery();
        //String valueToSeach;

        ArrayList<list> ctlist = cq.bookList2(jT.getText());
        String[] colName = {"Product Id", "Book Name", "Quantity", "Price", "Image"};
        Object[][] rows = new Object[ctlist.size()][5];
        for (int i = 0; i < ctlist.size(); i++) {
            rows[i][0] = ctlist.get(i).getPID();
            rows[i][1] = ctlist.get(i).getBNM();
            rows[i][2] = ctlist.get(i).getPrice();
            rows[i][3] = ctlist.get(i).getQuan();
            ImageIcon pic = new ImageIcon(new ImageIcon(ctlist.get(i).getBookPic()).getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH));
            rows[i][4] = pic;
            //  jTable.getColumnModel().getColumn(1).setPreferredWidth(40);
            MyModel mmd = new MyModel(rows, colName);
            jTable.setModel(mmd);
            jTable.setRowHeight(60);
            jTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        }
    }


    private void jTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTActionPerformed

    }//GEN-LAST:event_jTActionPerformed

    private void jTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTKeyReleased

    }//GEN-LAST:event_jTKeyReleased

    private void jTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTKeyTyped
        if (jT.getText() == "") {
            populateJtable();
        } else {
            populateJtable1();
        }
    }//GEN-LAST:event_jTKeyTyped

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        HomePage rgf = new HomePage();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        home.setBackground(Color.LIGHT_GRAY);
        home.setOpaque(true);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        home.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_homeMouseExited

    private void orderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseEntered
        order.setBackground(Color.LIGHT_GRAY);
        order.setOpaque(true);
    }//GEN-LAST:event_orderMouseEntered

    private void orderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseExited
        order.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_orderMouseExited

    private void olistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olistMouseExited
        olist.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_olistMouseExited

    private void olistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olistMouseEntered
        olist.setBackground(Color.LIGHT_GRAY);
        olist.setOpaque(true);
    }//GEN-LAST:event_olistMouseEntered

    private void olistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olistMouseClicked
        login rgf = new login();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_olistMouseClicked

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked
        order rgf = new order();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //this.dispose();

    }//GEN-LAST:event_orderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pic;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jT;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel olist;
    private javax.swing.JLabel order;
    // End of variables declaration//GEN-END:variables
}
