
import javax.swing.*;
import java.awt.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        /* JPanel somePanel = new JPanel(new GridBagLayout());
         somePanel.setBackground(new Color(0,0,0,120));*/

        this.setLocationRelativeTo(null);  //center to the screen
        scaleimage();
    }

    //scale cover image
//  this.setState(JFrame.ICONIFIED);
    public void scaleimage() {

        ImageIcon icon = new ImageIcon("F:\\New folder\\12.jpg");

        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(cover.getWidth(), cover.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        cover.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabelClickhere = new javax.swing.JLabel();
        jButton_login = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        cancel = new javax.swing.JButton();
        cover = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("aaa");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabelUsername.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUsername.setFont(new java.awt.Font("Sitka Display", 1, 20)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username :");
        jPanel1.add(jLabelUsername);
        jLabelUsername.setBounds(150, 170, 110, 50);

        jLabelPassword.setFont(new java.awt.Font("Sitka Display", 1, 20)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password :");
        jPanel1.add(jLabelPassword);
        jLabelPassword.setBounds(150, 220, 110, 50);

        username.setBackground(new java.awt.Color(18, 0, 0));
        username.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        jPanel1.add(username);
        username.setBounds(260, 180, 240, 30);

        password.setBackground(new java.awt.Color(18, 0, 0));
        password.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(260, 230, 240, 30);

        jLabelClickhere.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        jLabelClickhere.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClickhere.setText("Click Here To Create An Account");
        jLabelClickhere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClickhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClickhereMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClickhere);
        jLabelClickhere.setBounds(260, 319, 200, 50);

        jButton_login.setBackground(new java.awt.Color(0, 0, 0));
        jButton_login.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login.setText("Login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_login);
        jButton_login.setBounds(410, 280, 90, 29);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(260, 210, 240, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(260, 260, 240, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(260, 350, 190, 10);

        cancel.setBackground(new java.awt.Color(0, 0, 0));
        cancel.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(260, 280, 80, 30);

        cover.setText("LABEL");
        cover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                coverMouseDragged(evt);
            }
        });
        cover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coverMousePressed(evt);
            }
        });
        jPanel1.add(cover);
        cover.setBounds(0, 0, 880, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelClickhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClickhereMouseClicked
        registerform rgf = new registerform();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelClickhereMouseClicked

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        String uname = username.getText();
        String pass = String.valueOf(password.getPassword());
        if (uname.equals("admin") && pass.equals("1")) {
            Admin rgf = new Admin();
            rgf.setVisible(true);
            rgf.pack();
            rgf.setLocationRelativeTo(null);
            // rgf.setExtendedState(JFrame.MAXIMIZED_BOTH);
            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else {
            PreparedStatement ps;
            ResultSet rs;
            String query = "SELECT * FROM `register` WHERE `Username`=? AND `Password`=?";

            try {
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, uname);
                ps.setString(2, pass);
                rs = ps.executeQuery();

                if (rs.next()) {

                    HomePage rgf = new HomePage();
                    rgf.setVisible(true);
                    rgf.pack();
                    rgf.setLocationRelativeTo(null);
                    rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect Username Or Password", "Login Failed", HEIGHT);
                }

            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton_loginActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
    private int xMouse, yMouse;
    private void coverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coverMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_coverMousePressed

    private void coverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_coverMouseDragged

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel cover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabelClickhere;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
