
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
public class order extends javax.swing.JFrame {

    /**
     * Creates new form order
     */
    public order() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setOpacity(0.8f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        adress = new javax.swing.JLabel();
        quan = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        namef = new javax.swing.JTextField();
        phonef = new javax.swing.JTextField();
        quanf = new javax.swing.JTextField();
        pidf = new javax.swing.JTextField();
        addressf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(359, 423));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 347, 70));

        adress.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        adress.setText("Address      :");
        jPanel1.add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, 30));

        quan.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        quan.setText("Quantity     :");
        jPanel1.add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, 30));

        phone.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        phone.setText("Phone No    :");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 30));

        pid.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        pid.setText("Product ID  :");
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 30));

        name.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        name.setText("Your Name :");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        namef.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        namef.setBorder(null);
        namef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefActionPerformed(evt);
            }
        });
        jPanel1.add(namef, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 210, 30));

        phonef.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        phonef.setBorder(null);
        phonef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonefActionPerformed(evt);
            }
        });
        jPanel1.add(phonef, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 210, 30));

        quanf.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        quanf.setBorder(null);
        quanf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanfActionPerformed(evt);
            }
        });
        jPanel1.add(quanf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 210, 30));

        pidf.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        pidf.setBorder(null);
        jPanel1.add(pidf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, 30));

        addressf.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        addressf.setBorder(null);
        jPanel1.add(addressf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 210, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 210, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 210, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 210, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 210, 10));

        jButton1.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jButton2.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private int xMouse, yMouse;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void namefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefActionPerformed

    private void quanfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanfActionPerformed

    private void phonefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonefActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (verifdata()) {
            String yname = namef.getText();
            String phone = phonef.getText();
            String pid = pidf.getText();
            String quantity = quanf.getText();
            String addr = addressf.getText();
            olist c = new olist(yname, phone,pid, quantity, addr);
            listQuery cq = new listQuery();
            cq.insertOrderList(c);

        }
    

    }//GEN-LAST:event_jButton2MouseClicked
    public boolean verifdata() {
        if (namef.getText().equals("") || pidf.getText().equals("") || phonef.getText().equals("") || quanf.getText().equals("") || addressf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Some field missing", "Failed", HEIGHT);
            return false;

        } else {
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressf;
    private javax.swing.JLabel adress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namef;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phonef;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField pidf;
    private javax.swing.JLabel quan;
    private javax.swing.JTextField quanf;
    // End of variables declaration//GEN-END:variables
}
